// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type Object struct {
	Namespace      string `json:"namespace"`
	Path           string `json:"path"`
	Size           int64  `json:"size"`
	Etag           string `json:"etag"`
	ContentType    string `json:"content_type"`
	Filename       string `json:"filename"`
	Version        string `json:"version"`
	Deleted        int64  `json:"deleted"`
	AttributesJson string `json:"attributes_json"`
	CreatedAt      int64  `json:"created_at"`
	ModifiedAt     int64  `json:"modified_at"`
}

type Upload struct {
	UploadID       string `json:"upload_id"`
	Namespace      string `json:"namespace"`
	Path           string `json:"path"`
	Filename       string `json:"filename"`
	ContentType    string `json:"content_type"`
	AttributesJson string `json:"attributes_json"`
	TempPath       string `json:"temp_path"`
	BytesWritten   int64  `json:"bytes_written"`
	ExpectedSize   int64  `json:"expected_size"`
	Status         string `json:"status"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}
