// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: object.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const copyObjectRecord = `-- name: CopyObjectRecord :exec
INSERT INTO objects (
  namespace,
  path,
  size,
  etag,
  content_type,
  filename,
  version,
  deleted,
  attributes_json,
  created_at,
  modified_at
)
SELECT
  ?, ?, size, etag, content_type, filename, ?, deleted, attributes_json, ?, ?
FROM objects
WHERE objects.namespace = ? AND objects.path = ?
`

type CopyObjectRecordParams struct {
	Namespace   string `json:"namespace"`
	Path        string `json:"path"`
	Version     string `json:"version"`
	CreatedAt   int64  `json:"created_at"`
	ModifiedAt  int64  `json:"modified_at"`
	Namespace_2 string `json:"namespace_2"`
	Path_2      string `json:"path_2"`
}

func (q *Queries) CopyObjectRecord(ctx context.Context, arg CopyObjectRecordParams) error {
	_, err := q.db.ExecContext(ctx, copyObjectRecord,
		arg.Namespace,
		arg.Path,
		arg.Version,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.Namespace_2,
		arg.Path_2,
	)
	return err
}

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM objects
WHERE namespace = ? AND path = ?
`

type DeleteObjectParams struct {
	Namespace string `json:"namespace"`
	Path      string `json:"path"`
}

func (q *Queries) DeleteObject(ctx context.Context, arg DeleteObjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteObject, arg.Namespace, arg.Path)
	return err
}

const getObject = `-- name: GetObject :one
SELECT
  namespace,
  path,
  size,
  etag,
  content_type,
  filename,
  version,
  deleted,
  attributes_json,
  created_at,
  modified_at
FROM objects
WHERE objects.namespace = ? AND objects.path = ?
`

type GetObjectParams struct {
	Namespace string `json:"namespace"`
	Path      string `json:"path"`
}

func (q *Queries) GetObject(ctx context.Context, arg GetObjectParams) (Object, error) {
	row := q.db.QueryRowContext(ctx, getObject, arg.Namespace, arg.Path)
	var i Object
	err := row.Scan(
		&i.Namespace,
		&i.Path,
		&i.Size,
		&i.Etag,
		&i.ContentType,
		&i.Filename,
		&i.Version,
		&i.Deleted,
		&i.AttributesJson,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listObjectsByPrefix = `-- name: ListObjectsByPrefix :many
SELECT
  namespace,
  path,
  size,
  etag,
  content_type,
  filename,
  version,
  deleted,
  attributes_json,
  created_at,
  modified_at
FROM objects
WHERE namespace = ?
  AND path LIKE ? || '%'
ORDER BY path
LIMIT ? OFFSET ?
`

type ListObjectsByPrefixParams struct {
	Namespace string         `json:"namespace"`
	Column2   sql.NullString `json:"column_2"`
	Limit     int64          `json:"limit"`
	Offset    int64          `json:"offset"`
}

func (q *Queries) ListObjectsByPrefix(ctx context.Context, arg ListObjectsByPrefixParams) ([]Object, error) {
	rows, err := q.db.QueryContext(ctx, listObjectsByPrefix,
		arg.Namespace,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Object
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.Namespace,
			&i.Path,
			&i.Size,
			&i.Etag,
			&i.ContentType,
			&i.Filename,
			&i.Version,
			&i.Deleted,
			&i.AttributesJson,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveObjectRecord = `-- name: MoveObjectRecord :exec
UPDATE objects
SET namespace = ?, path = ?, modified_at = ?
WHERE namespace = ? AND path = ?
`

type MoveObjectRecordParams struct {
	Namespace   string `json:"namespace"`
	Path        string `json:"path"`
	ModifiedAt  int64  `json:"modified_at"`
	Namespace_2 string `json:"namespace_2"`
	Path_2      string `json:"path_2"`
}

func (q *Queries) MoveObjectRecord(ctx context.Context, arg MoveObjectRecordParams) error {
	_, err := q.db.ExecContext(ctx, moveObjectRecord,
		arg.Namespace,
		arg.Path,
		arg.ModifiedAt,
		arg.Namespace_2,
		arg.Path_2,
	)
	return err
}

const upsertObject = `-- name: UpsertObject :exec
INSERT INTO objects (
  namespace,
  path,
  size,
  etag,
  content_type,
  filename,
  version,
  deleted,
  attributes_json,
  created_at,
  modified_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(namespace, path) DO UPDATE SET
  size = excluded.size,
  etag = excluded.etag,
  content_type = excluded.content_type,
  filename = excluded.filename,
  version = excluded.version,
  deleted = excluded.deleted,
  attributes_json = excluded.attributes_json,
  modified_at = excluded.modified_at
`

type UpsertObjectParams struct {
	Namespace      string `json:"namespace"`
	Path           string `json:"path"`
	Size           int64  `json:"size"`
	Etag           string `json:"etag"`
	ContentType    string `json:"content_type"`
	Filename       string `json:"filename"`
	Version        string `json:"version"`
	Deleted        int64  `json:"deleted"`
	AttributesJson string `json:"attributes_json"`
	CreatedAt      int64  `json:"created_at"`
	ModifiedAt     int64  `json:"modified_at"`
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) error {
	_, err := q.db.ExecContext(ctx, upsertObject,
		arg.Namespace,
		arg.Path,
		arg.Size,
		arg.Etag,
		arg.ContentType,
		arg.Filename,
		arg.Version,
		arg.Deleted,
		arg.AttributesJson,
		arg.CreatedAt,
		arg.ModifiedAt,
	)
	return err
}
