// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CopyObjectRecord(ctx context.Context, arg CopyObjectRecordParams) error
	CreateUploadRecord(ctx context.Context, arg CreateUploadRecordParams) error
	DeleteObject(ctx context.Context, arg DeleteObjectParams) error
	GetObject(ctx context.Context, arg GetObjectParams) (Object, error)
	GetUploadRecord(ctx context.Context, uploadID string) (Upload, error)
	ListObjectsByPrefix(ctx context.Context, arg ListObjectsByPrefixParams) ([]Object, error)
	MarkUploadAborted(ctx context.Context, arg MarkUploadAbortedParams) error
	MarkUploadCommitted(ctx context.Context, arg MarkUploadCommittedParams) error
	MoveObjectRecord(ctx context.Context, arg MoveObjectRecordParams) error
	UpdateUploadProgress(ctx context.Context, arg UpdateUploadProgressParams) error
	UpsertObject(ctx context.Context, arg UpsertObjectParams) error
}

var _ Querier = (*Queries)(nil)
