// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload.sql

package sqlcgen

import (
	"context"
)

const createUploadRecord = `-- name: CreateUploadRecord :exec
INSERT INTO uploads (
  upload_id,
  namespace,
  path,
  filename,
  content_type,
  attributes_json,
  temp_path,
  bytes_written,
  expected_size,
  status,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUploadRecordParams struct {
	UploadID       string `json:"upload_id"`
	Namespace      string `json:"namespace"`
	Path           string `json:"path"`
	Filename       string `json:"filename"`
	ContentType    string `json:"content_type"`
	AttributesJson string `json:"attributes_json"`
	TempPath       string `json:"temp_path"`
	BytesWritten   int64  `json:"bytes_written"`
	ExpectedSize   int64  `json:"expected_size"`
	Status         string `json:"status"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateUploadRecord(ctx context.Context, arg CreateUploadRecordParams) error {
	_, err := q.db.ExecContext(ctx, createUploadRecord,
		arg.UploadID,
		arg.Namespace,
		arg.Path,
		arg.Filename,
		arg.ContentType,
		arg.AttributesJson,
		arg.TempPath,
		arg.BytesWritten,
		arg.ExpectedSize,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUploadRecord = `-- name: GetUploadRecord :one
SELECT
  upload_id,
  namespace,
  path,
  filename,
  content_type,
  attributes_json,
  temp_path,
  bytes_written,
  expected_size,
  status,
  created_at,
  updated_at
FROM uploads
WHERE upload_id = ?
`

func (q *Queries) GetUploadRecord(ctx context.Context, uploadID string) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUploadRecord, uploadID)
	var i Upload
	err := row.Scan(
		&i.UploadID,
		&i.Namespace,
		&i.Path,
		&i.Filename,
		&i.ContentType,
		&i.AttributesJson,
		&i.TempPath,
		&i.BytesWritten,
		&i.ExpectedSize,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUploadAborted = `-- name: MarkUploadAborted :exec
UPDATE uploads
SET status = 'aborted', updated_at = ?
WHERE upload_id = ?
  AND status = 'active'
`

type MarkUploadAbortedParams struct {
	UpdatedAt int64  `json:"updated_at"`
	UploadID  string `json:"upload_id"`
}

func (q *Queries) MarkUploadAborted(ctx context.Context, arg MarkUploadAbortedParams) error {
	_, err := q.db.ExecContext(ctx, markUploadAborted, arg.UpdatedAt, arg.UploadID)
	return err
}

const markUploadCommitted = `-- name: MarkUploadCommitted :exec
UPDATE uploads
SET status = 'committed', updated_at = ?
WHERE upload_id = ?
  AND status = 'active'
`

type MarkUploadCommittedParams struct {
	UpdatedAt int64  `json:"updated_at"`
	UploadID  string `json:"upload_id"`
}

func (q *Queries) MarkUploadCommitted(ctx context.Context, arg MarkUploadCommittedParams) error {
	_, err := q.db.ExecContext(ctx, markUploadCommitted, arg.UpdatedAt, arg.UploadID)
	return err
}

const updateUploadProgress = `-- name: UpdateUploadProgress :exec
UPDATE uploads
SET bytes_written = ?, updated_at = ?
WHERE upload_id = ?
  AND status = 'active'
`

type UpdateUploadProgressParams struct {
	BytesWritten int64  `json:"bytes_written"`
	UpdatedAt    int64  `json:"updated_at"`
	UploadID     string `json:"upload_id"`
}

func (q *Queries) UpdateUploadProgress(ctx context.Context, arg UpdateUploadProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadProgress, arg.BytesWritten, arg.UpdatedAt, arg.UploadID)
	return err
}
